--- 
- hosts: 172.31.39.3
  become: yes
  tasks:
          - name: i want to create file
            file:
                     path: /home/ubuntu/myf1.txt
                     state: touch

          - name: i want to install webserver
            apt: 
                     name: apache2
                     state: present           