--- 
- hosts: 172.31.39.3
  become: yes
  tasks:
          - include_tasks: myfile.yml

          - name: i want to install webserver
            apt: 
                     name: apache2
                     state: present  

          - name : i want to change template 
            template:
                     src: myjinja.j2
                     dest:  /var/www/html/index.html

                 