--- 
- hosts: 172.31.39.3
  become: yes
  tasks:
          - include_tasks: myfile.yml

          - name: i want to install webserver
            apt: 
                     name: apache2
                     state: present           