--- 
- hosts: webserverHost 
  become: yes
  tasks: 
          
          - name: i want install webserver
            apt:
             
                   name: "{{mywebserveronubuntu}}"
                   state: present

            when: ansible_os_family=="Debian"  

          - name: i want start/stop webserver on ubuntu
            service:

                  name: "{{mywebserveronubuntu}}"
                  state: started   

            when: ansible_os_family=="Debian" 

          - name: i want install webserver on Redhat 
            yum:
                  name: "{{mywebserveronRedhat}}"
                  state: present 

            when: ansible_os_family=="RedHat"

          - name: i want to start/stop webserver on Redhat
            service: 
                  name: "{{mywebserveronRedhat}}"
                  state: started

            when: ansible_os_family=="RedHat"     
             
                       
          
             
                       