--- 
- hosts: 172.31.39.3
  become: yes 
  vars: 
         myvar1: tree 
         myvar2: wget 
         myvar3: git 
  tasks: 
       - name : i want to display vars value 
         debug:
                 msg: "{{myvar1}}"      
                 
       - name : i want to display vars value
         debug:
                 msg: "{{myvar2}}"          

       - name : i want install package
         apt: 
                name: "{{item}}"
                state: present 
         when: ansible_os_family=="Debian"

         loop: 
         - "{{myvar1}}"
         - "{{myvar2}}"
         - "{{myvar3}}"