--- 
- hosts: all 
  become: yes
  tasks: 
          
          - name: i want install web
            apt:
             
                   name: "{{mywebserveronubuntu}}"
                   state: present

            when: ansible_os_family=="Debian"  

          - name: i want start/stop on ubuntu
            service:

                   name: "{{mywebserveronubuntu}}"
                   state: started   

            when: ansible_os_family=="Debian" 
          - name: i want install webserver on Redhat 
            yum:
                  name: "{{mywebserveronubuntu}}"
                  state: latest

            when: ansible_os_family=="RedHat"

          - name: i want to start/stop webserver on Redhat
            service: 
                   name: "{{mywebserveronubuntu}}"
                   state: started

            when: ansible_os_family=="RedHat"     
             
                       
          
             
                       