---
# Step 7:  Configure Tomcat Web Management Interface
- name :  editing the tomcat-users
  template:
             src: template/templateuser.j2
             dest: /opt/tomcat/conf/tomcat-users.xml

- name :  change manager context file
  template:
             src: template/managerapp.j2
             dest:  /opt/tomcat/webapps/manager/META-INF/context.xml

- name :  change host manager context file
  template:
             src: template/hostmanagerapp.j2
             dest:  /opt/tomcat/webapps/host-manager/META-INF/context.xml

